version: "3.9"

services:
  db:
    image: mysql:8
    container_name: metadata_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: metadata_db
    ports:
      - "3306:3306"

  api:
    build: .
    container_name: metadata_api
    restart: always
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - "8000:8000"
